# Generated by Django 3.1.2 on 2020-10-31 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_author_image_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catogory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catogoryName',
            new_name='categoryName',
        ),
    ]
